### ISSUE TITLE
Pull Requst 템플릿 생성

### ISSUE THREAD

**Issue by HongEunbeen** [euphony-io/account-touch#12]
- [x] PR template markdown 생성

**Comment by designe** [comment]
@HongEunbeen 은빈님! PR 하신 후 바로 merge 하시고 계시군요!
팀원 두분께 리뷰 요청하시면서 진행하시는게 좋을 것 같아요 :)

은빈님이 엄청 Pull Request  매너가 좋으셔서 (작은 단위 PR)
다른 팀원들도 충분히 빠르게 리뷰 가능하리라 봅니다 :)

**Comment by HongEunbeen** [comment]
@designe 안녕하세요! 코멘트 감사합니다!

해당 부분은 2차 회의에서 정해진 template를 설정하는 단순 PR이라고 생각해 [해당 PR 설명](https://github.com/euphony-io/account-touch/pull/13)으로 코드 리뷰 생략이라고 남겼습니다⚙

[2차 회의록 5번 부분](https://github.com/orgs/euphony-io/teams/euphoever/discussions/11)에 리뷰 방법을 정리했는데,  단순 문서 처리가 아닌 개발 시에는 서로 리뷰를 진행하기로 했습니다!

**Comment by designe** [comment]
@HongEunbeen 그라운드룰을 그렇게 정하셨군요.
빠른 답변 감사드려요 :+1: 혼자 개발하시는 것처럼 보여서 잠깐 깜짝 놀라서 여쭤보았습니다 ㅋㅋㅋㅋㅋ
